version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build Docker image
          command: |
            docker build -t shihabsami/sept-take-home-assignment-2:latest .
      - run:
          name: Push Docker image to Dockerhub
          command: |
            docker push shihabsami/sept-take-home-assignment-2:latest

workflows:
  build:
    jobs:
      - build